### ISSUE TITLE
Only 1 enchant

### ISSUE THREAD

**Issue by SaltBotRepo** [N3kas/AdvancedEnchantments#12] opened 2018-05-06 14:23 UTC
When i add custom enchants using the book. It adds 1 then doesn't display any others

**Comment by Jezuuh** [comment] 2018-05-07 10:15
Also have the same issue, also getting internal server error when trying to give myself certain items.

Using Paper-1.8.8 and here are the error messages from the console:

`7.05 04:10:17 [Server] INFO Caused by: java.lang.NullPointerException
07.05 04:10:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
07.05 04:10:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
07.05 04:10:17 [Server] INFO org.bukkit.event.EventException
07.05 04:10:17 [Server] ERROR Could not pass event InventoryClickEvent to AdvancedEnchantments v3.1.8`

Only Just installed the plugin and I love it so far, however these issues are kinda annoying. Only one enchant is displaying.

**Comment by N3kas** [comment] 2018-05-07 10:32
Yup, it’s going to be fixed with today’s update!

**Comment by Jezuuh** [comment] 2018-05-07 10:35
Brilliant thankyou for the quick reply my friend!

**Closed** 2018-05-08 13:13 UTC
